import { test, expect } from '@playwright/test';
test('loginpersonnel1', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('jira');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('123456');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.screenshot({path:"test-results/screenshot14.png",fullPage:true});
});
test('loginpersonnel2', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('jira');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('123456');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.screenshot({path:"test-results/screenshot15.png",fullPage:true});
});
test('loginpersonnel3', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('jira');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('123456');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.screenshot({path:"test-results/screenshot16.png",fullPage:true});
});
test('loginpersonnel4', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('jira');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('123456');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.screenshot({path:"test-results/screenshot17.png",fullPage:true});
});
test('loginpersonnel5', async ({ page }) => {
  await page.goto('https://computer.surin.rmuti.ac.th/sc/pro/');
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้งาน' }).fill('admin');
  await page.getByRole('textbox', { name: 'รหัสผ่าน' }).fill('admin.min');
  await page.getByRole('button', { name: 'เข้าสู่ระบบ' }).click();
  await page.getByRole('link', { name: '✏️เพิ่มบุคลากร' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).click();
  await page.getByRole('textbox', { name: 'ชื่อผู้ใช้ (Username)' }).fill('jira');
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).click();
  await page.getByRole('textbox', { name: 'รหัสผ่าน (Password)' }).fill('123456');
  await page.getByRole('button', { name: ' บันทึก' }).click();
  await page.screenshot({path:"test-results/screenshot18.png",fullPage:true});
});